account/urls.py
from django.urls import path
from . import views
# from django.contrib.auth.views import login, logout

app_name = 'account'
urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    # path('login/', login, { 'template_name':'accouts/login.html' }),
    # path('logout/', logout, { 'template_name':'accouts/logout.html' }),

    path('register/', views.register , name='register'),

]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.addForm, name='addForm'),
    path('add/content/', views.addCon, name='addCon'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.editCon, name='edit'),
    path('<int:pk>/edited/', views.editedCon , name='edited'),
    path('<int:pk>/edit/delete/', views.deleteCon, name='delete'),

    path('<int:blog_id>/comment', views.comment, name='comment'),
    path('<int:blog_id>/comment/<int:comment_id>', views.delComment, name='delcomment'),

    path('search/<str:search>', views.searchAuthor, name='searched'),
    path('search/', views.search, name='search'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('login/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    # first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    # last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    # email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

account/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission, User
from account.forms import SignUpForm

def login(request):
    if(request.method == "POST"):
        user_id = request.POST['id']
        user_pass = request.POST['password']
        print(user_id)
        print(user_pass)

        user = authenticate(request, username=user_id, password=user_pass)
        if user is not None:
            auth_login(request, user)
            return redirect('/blog/')
        else:
            return render(request, 'account/failform.html')
        
    elif(request.method == "GET"):
        print("loginForm")
        return render(request, 'account/loginForm.html')
    
def logout(request):
    auth_logout(request)
    return redirect('/blog/')

def get_permission(perm):
    if(perm == '3'):
        return ['add_blog','change_blog','delete_blog','add_comment','change_comment','delete_comment']
    elif(perm == '2'):
        return ['add_blog','change_blog','delete_blog','delete_comment']
    elif(perm == '1'):
        return ['add_blog','delete_blog','delete_comment']
    elif(perm == '0'):
        return ['delete_comment'] 
    else:
        return []

def register(request):
    if(request.method == "POST"):
        form = SignUpForm(request.POST)
        
        if form.is_valid():
            form.save()
            print('SAVE already')
            u = User.objects.get(username=request.POST['username'])
            u.is_staff = True
            perms = get_permission(request.POST['perm'])
            print(perms)
            for perm in perms:
                permission = Permission.objects.get(codename=perm)
                u.user_permissions.add(permission)
            print('update permission already')

        else:
            print('testetewtew')
            return render(request, 'account/failformRegis.html')
    elif(request.method == "GET"):
        print("regisForm")
        form = SignUpForm()
        permission = ['add_blog','change_blog','delete_blog','add_comment','change_comment','delete_comment']
        return render(request, 'account/regisForm.html', {'form':form ,'permission': permission})

    return HttpResponseRedirect(reverse('blog:index'))

account/templates/base_layout.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->

  </head>

  <body>
      <div style="padding: 10px">
        <hr>
        <h1><a href="{% url 'blog:index' %}">Unix Dev</a></h1>
        {% if user.status_login %}
          <!-- <a href="{% url 'blog:addForm' %}">AddContent</a> -->
          <a href="{% url 'account:logout' %}">Logout</a>
        {% else %}
          <a href="{% url 'account:login' %}">Login</a>
          <a href="{% url 'account:register' %}">Register</a>
        {% endif %}
        <div align="center">
          <hr>
            <form action="{% url 'blog:search' %}" method="post">
                {% csrf_token %}
                    Search : <input type="text" name="search"><input type="submit" value="search">
            </form>
          <hr>
        </div>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>

        <hr>
        Footer
        {% if user.status_login %}
          <p>User : {{user.user_name}}<p>
        {% endif %}
        <hr>
    </div>
  </body>

</html>