blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.addForm, name='addForm'),
    path('add/content/', views.addCon, name='addCon'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.editCon, name='edit'),
    path('<int:pk>/edited/', views.editedCon , name='edited'),
    path('<int:pk>/edit/delete/', views.deleteCon, name='delete'),

    path('<int:blog_id>/comment', views.comment, name='comment'),
    path('<int:blog_id>/comment/<int:comment_id>', views.delComment, name='delcomment'),

    path('search/<str:search>', views.searchAuthor, name='searched'),
    path('search/', views.search, name='search'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('login/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Comment(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    content = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse 

# from django.views import generic

from django.contrib.auth.models import User
from .models import Blog, Comment
from django.core.paginator import Paginator

def auth_permission(request, permission):
    print('auth_permission') 
    result = False
    if(request.user.has_perm(permission) or 'admin' == str(request.user)):
        result = True
    else:
        result = False
    return result 

def sessionResult(request):
    if request.session.keys():
        return True
    else: 
        return False

def index(request):
    print('index')
    list_title = Blog.objects.order_by('-created_at')
    paginator = Paginator(list_title, 5)

    page = request.GET.get('page')
    blogs = paginator.get_page(page)

    return render(request, 'blog/index.html', {'list' : blogs, 'user' : { 'user_name': request.user ,'status_login': sessionResult(request)}})

def addForm(request):
    print('addForm')
    if((request.user.has_perm('blog.add_blog') or 'admin' == str(request.user))):
        edit = True
    else:
        edit = False

    return render(request, 'blog/formAddCon.html' , {'state' :  edit ,'user' : { 'user_name': request.user ,'status_login': sessionResult(request)}} )

def detail(request,pk):
    # can Edot Content
    blog = get_object_or_404(Blog, pk=pk)
    user_check = get_object_or_404(User, pk=blog.user_id) # get name user form blog
    if((request.user.has_perm('blog.change_blog') and str(user_check.username) == str(request.user)) or 'admin' == str(request.user)):
        edit = True
    else:
        edit = False

    data = {
        'blog': blog, 
        'credit':user_check.username ,
        'edit': edit,
        'user':{
            'user_name': request.user ,
            'status_login': sessionResult(request)
            },
        'user_delete_comment' : 0,
        'comment': False
        }
        
    # can Edot Comment
    if request.session.keys():
        data['comment'] = True
        if 'admin' == str(request.user):
            data['user_delete_comment'] = True
        elif request.user.has_perm('blog.delete_comment'):
            data['user_delete_comment'] = int(request.session['_auth_user_id'])
            
            
    print(data['user_delete_comment'])
    return render(request, 'blog/detail.html', data)

def editCon(request,pk):
    print('editCon')
    blog = Blog.objects.get(pk=pk)
    print('blog edit : id ',blog.id)
    print('blog edit : title ',blog.title)
    return render(request, 'blog/edit.html', {'blog': blog, 'user':{ 'user_name': request.user ,'status_login': sessionResult(request)}})

def editedCon(request,pk):
    print('editedCon')
    try:
        result = auth_permission(request, 'blog.change_blog')
        blog = Blog.objects.get(pk=pk)
    except (KeyError):
        pass
    else:
        if(result):
            blog.title = request.POST['title']
            blog.content = request.POST['content']
            blog.save()
            return HttpResponseRedirect(reverse('blog:index'))
        else:
            return render(request, 'blog/errorPerm.html')
    
def addCon(request):
    print('addCon')
    try:
        result = auth_permission(request, 'blog.add_blog')
        print('add Title : ',request.POST['title'])
        print('add Content : ',request.POST['content'])
    except (KeyError):
        pass
    else:
        if(result):
            blog = Blog(title = request.POST['title'], content = request.POST['content'], user_id=request.session['_auth_user_id'])
            blog.save()
            return HttpResponseRedirect(reverse('blog:index'))
        else:
            return render(request, 'blog/errorPerm.html')

def deleteCon(request,pk):
    print("deleteCon")
    try:
        result = auth_permission(request, 'blog.delete_blog')
        blog = Blog.objects.get(pk=pk)
    except (KeyError):
        pass
    else:
        if(result):
            blog.delete()
            return HttpResponseRedirect(reverse('blog:index'))
        else:
            print('asdsadasd')
            return render(request, 'blog/errorPerm.html')

def comment(request,blog_id):
    print("addcomment")
    result = auth_permission(request, 'blog.add_comment')
    if(request.method == "POST" and result == True):
        comment = Comment(content_id=blog_id,  comment= request.POST['comment'], user_id=request.session['_auth_user_id'])
        comment.save()
        return HttpResponseRedirect(reverse('blog:detail', args=(blog_id,)))
    else:
        return render(request, 'blog/errorPerm.html')

def delComment(request,blog_id,comment_id):
    print("delComment")
    try:
        result = auth_permission(request, 'blog.delete_comment')
        comment = Comment.objects.get(pk=comment_id)
    except (KeyError):
        pass
    else:
        if(result): 
            comment.delete()
            return HttpResponseRedirect(reverse('blog:detail', args=(blog_id,)))
        else:
            return render(request, 'blog/errorPerm.html')


def search(request):
    print("search")
    if(request.method == "POST"):
        if(request.POST['search'] == ''):
            return HttpResponseRedirect(reverse('blog:index'))
        else:
            return HttpResponseRedirect(reverse('blog:searched', args=(request.POST['search'],)))
    else:
        return HttpResponseRedirect(reverse('blog:index'))



def searchAuthor(request, search):
    print("searchAuthor")
    data = {
        # 'list' : listEmp, 
        'author':search, 
        'user' : { 
            'user_name': request.user ,
            'status_login': sessionResult(request)
            }
        }
        
    dictUser = {}
    try:
        user_check = User.objects.filter(username__contains=search)
        print(user_check)
        for user in user_check:
            dictBlog = {}
            blogs = Blog.objects.all().filter(user_id=user.id)
            if(blogs):
                for blog in blogs:
                    dictBlog[str(blog.id)] = blog
                dictUser[str(user)] = dictBlog

        data = {
            'dictUser' : dictUser, 
            'author':search, 
            'user' : { 
                'user_name': request.user ,
                'status_login': sessionResult(request)
                }
            }
        print('pass')
        return render(request, 'blog/searchAuthor.html', data)
    except:
        print('ssadasd')
        return render(request, 'blog/searchAuthor.html', {'user' : { 'user_name': request.user ,'status_login': sessionResult(request)}})

blog/templates/blog/detail.html
{% extends 'base_layout.html' %}    
{% block content %}
<div>
    <h1>Detail</h1>
    <h3>{{ blog.title }}</h3>
    <div>
        {{ blog.content }}
    </div>
    {% if edit %}
        <a href="{% url 'blog:edit' blog.id %}">Edit</a>
    {% endif %}
    <p>Credit : {{credit}}</p>
    <br>

    <ul>
    {% for comment in blog.comment_set.all %}
        <li style="font-weight: bold">{{ comment.comment }}</li>name : {{ comment.user }}
        {% if user_delete_comment == comment.user_id or user_delete_comment == True %}
            <a href="{% url 'blog:delcomment' blog.id  comment.id %}">delete</a>
        {% endif %}
    {% endfor %}
    </ul>
    {% if True %}
    <form action="{% url 'blog:comment' blog.id %}" method="post">
        {% csrf_token %}
            <p>Comment</p>
                <textarea name="comment" rows="4" cols="70"></textarea>
            <br>
            <br>
            <input type="submit" value="Comment">
    </form>
    {% endif %}
</div>
    
{% endblock %}

blog/templates/blog/edit.html
{% extends 'base_layout.html' %}    
{% block content %}
<div>
    <h1>Edit</h1>
    <form action="{% url 'blog:edited' blog.id %}" method="post">
            {% csrf_token %}
            <p>Title</p>
                <input type="text" name="title" value="{{ blog.title }}"><br>
            <p>Content</p>
                <textarea name="content" rows="4" cols="70" >{{ blog.content }}</textarea>
            <br>
            <a href="{% url 'blog:detail' blog.id %}">Back</a>
            <input type="submit" value="Edit">
            <button><a href="{% url 'blog:delete' blog.id %}">Delete</a></button>
    </form>
</div>
    
{% endblock %}

blog/templates/blog/errorPerm.html
{% extends 'base_layout.html' %}    
{% block content %}
<div align="center">
    Error Permisson
</div>
    
{% endblock %}

blog/templates/blog/formAddCon.html
{% extends 'base_layout.html' %}    
{% block content %}
<div align="center">
    <h1>Create</h1>
    {% if state %}
        <form action="{% url 'blog:addCon' %}" method="post">
            {% csrf_token %}
                <p>Title</p>
                    <input type="text" name="title"><br>
                <p>Content</p>
                    <textarea name="content" rows="4" cols="20"></textarea>
                <br>
                <input type="submit" value="Submit">
        </form>
    {% else %}
        <p> Can't Create Content </p>
    {% endif %}
</div>
    
{% endblock %}

blog/templates/blog/index.html
{% extends 'base_layout.html' %}    
{% block content %}

    <h1>Home</h1>
    {% if list %}
        <ul>
            {% if user.status_login %}
                <button><a href="{% url 'blog:addForm' %}">AddContent</a></button>
            {% endif %}
            {% for item in list %}
                <li style="font-weight: bold">{{item.title}}</li>date : {{item.created_at}} <a href="{% url 'blog:detail' item.id %}">Readmore</a>
            {% endfor %}
        </ul>
        <br>
        <div class="pagination" style="text-align: center; display: block;">
            <a href="?page=1">first</a>
            <div style="display: inline; padding-left: 30px; padding-right: 30px">
                {% for i in list.paginator.page_range %}
                    {% if list.number == i %} 
                        <strong><a href="?page={{i}}">{{i}}</a></strong>
                    {% else %}
                        <a href="?page={{i}}">{{i}}</a>
                    {% endif %}
                {% endfor %}
            </div>
            <a href="?page={{ list.paginator.num_pages }}">last</a>
            
        </div>
    {% else %}
        <p>This blog is Empty</p>
        <button><a href="{% url 'blog:addForm' %}">AddContent</a></button>
    {% endif %}

{% endblock %}

blog/templates/blog/searchAuthor.html
{% extends 'base_layout.html' %}    
{% block content %}
    <h3>Seact Author : {{author}}</h3>
    {% if dictUser %}
        <ul>
            {% for user_i, value_i in dictUser.items %}
                <li>{{ user_i }}</li>
                <ul>
                {% for id, title in value_i.items %}
                    <li><a  href="{% url 'blog:detail' id %}">{{title}}</a></li>
                {% endfor %}    
                </ul> 
            {% endfor %}
        </ul>
    {% else %}
        <p>No result</p>
    {% endif %}

{% endblock %}